language: python
python:
- '3.6'
cache: pip
services:
- docker
install:
- pip install -e .
script:
- python nyoka/tests/test_import.py
- python nyoka/tests/_install_dependencies.py
- python nyoka/tests/test_skl_to_pmml_UnitTest.py
- python nyoka/tests/test_xgboost_to_pmml_UnitTest.py
- python nyoka/tests/test_lgbm_to_pmml_UnitTest.py
- python nyoka/tests/test_keras_to_pmml_UnitTest.py
- python nyoka/tests/test_statsmodels_to_pmml_UnitTest.py
- python nyoka/tests/test_retinanet_to_pmml_UnitTest.py
- python nyoka/tests/setup_server.py
- python nyoka/tests/testScoreWithAdapaLgbm.py
- python nyoka/tests/testScoreWithAdapaSklearn.py
- python nyoka/tests/testScoreWithAdapaXgboost.py
- python nyoka/tests/testScoreWithAdapaKeras.py
after_success:
- travis_wait 30 py.test  --cov-report term --cov=nyoka/
- codecov
notifications:
  email:
    recipients:
    - maintainer@nyoka.org
    on_success: never
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_a6521150e702_key -iv $encrypted_a6521150e702_iv
  -in secrets.zip.enc -out secrets.zip -d
- unzip secrets.zip
- ls
- echo "$DOCKER_PW" | docker login -u "$DOCKER_UN" --password-stdin
- docker run -d -p 8080:8080 --memory="5g" store/softwareag/zementis-server:10.4.0.1
- docker ps