language: python
python:
  - "3.6"
cache: pip
# install: "pip install git+https://github.com/nyoka-pmml/nyoka.git@dev"
script:
  # - git clone --branch=dev https://github.com/nyoka-pmml/nyoka.git
  # - cd nyoka
  - python nyoka/tests/test_import.py
  - python nyoka/tests/_install_dependencies.py
  - python nyoka/tests/test_skl_to_pmml_UnitTest.py
  - python nyoka/tests/test_xgboost_to_pmml_UnitTest.py
  - python nyoka/tests/test_lgbm_to_pmml_UnitTest.py
  - python nyoka/tests/test_keras_to_pmml_UnitTest.py
  - python nyoka/tests/test_statsmodels_to_pmml_UnitTest.py
  - py.test  --cov-report term --cov=nyoka/

after_script:
  - codecov

notifications:
  email:
    recipients:
      - maintainer@nyoka.org
    on_success: never
    on_failure: always
