language: python
python:
  - "3.5"
  - "3.6"
cache: pip
install: "pip install -r nyoka/tests/requirements.txt"
before_script:
  - git clone --recursive https://github.com/dmlc/xgboost
  - cd xgboost
  - make -j4
  - cd python-package
  - python setup.py install
  - cd ../../
  - git clone --recursive https://github.com/Microsoft/LightGBM
  - cd LightGBM
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - cd ../../
  - sudo apt-get update && \
  - sudo apt-get install build-essential software-properties-common -y && \
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && \
  - sudo apt-get update && \
  - sudo apt-get install gcc-snapshot -y && \
  - sudo apt-get update && \
  - sudo apt-get install gcc-6 g++-6 -y && \
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6 && \
  - sudo apt-get install gcc-4.8 g++-4.8 -y && \
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
script: 
  - python nyoka/tests/skl_to_pmml_UnitTest.py
  - python nyoka/tests/xgboost_to_pmml_UnitTest.py
  - python nyoka/tests/lgbm_to_pmml_UnitTest.py
notifications:
  email:
    recipients:
      - maintainer@nyoka.org
    on_success: never
    on_failure: always
