language: python
python:
  - "3.5"
  - "3.6"
cache: pip
install: "pip install -r nyoka/tests/requirements.txt"
before_script:
  - git clone --recursive https://github.com/dmlc/xgboost
  - cd xgboost
  - make -j4
  - cd python-package
  - python setup.py install
  - cd ../../
script: 
  - python nyoka/tests/skl_to_pmml_UnitTest.py
  - python nyoka/tests/xgboost_to_pmml_UnitTest.py
notifications:
  email:
    recipients:
      - maintainer@nyoka.org
    on_success: never
    on_failure: always
