language: python

python:
  - "3.6"

cache: pip

before_install:
  - openssl aes-256-cbc -K $encrypted_7bf883d4fa3b_key -iv $encrypted_7bf883d4fa3b_iv -in nn.tar.enc -out nn.tar -d
  - tar xvf nn.tar
  - ls

install: "pip install -e ."

script:
  - python nyoka/tests/test_import.py
  - python nyoka/tests/_install_dependencies.py
  - python nyoka/tests/test_skl_to_pmml_UnitTest.py
  - python nyoka/tests/test_xgboost_to_pmml_UnitTest.py
  - python nyoka/tests/test_lgbm_to_pmml_UnitTest.py
  - python nyoka/tests/test_keras_to_pmml_UnitTest.py
  - python nyoka/tests/test_statsmodels_to_pmml_UnitTest.py
  - python nyoka/tests/test_retinanet_to_pmml_UnitTest.py
  - python nyoka/tests/testScoreWithAdapaKeras.py
  - python nyoka/tests/testScoreWithAdapaLgbm.py
  - python nyoka/tests/testScoreWithAdapaSklearn.py
  - python nyoka/tests/testScoreWithAdapaXgboost.py
  - py.test  --cov-report term --cov=nyoka/

after_success:
  - codecov

notifications:
  email:
    recipients:
      - maintainer@nyoka.org
    on_success: never
    on_failure: always
