ignore:
  - "nyoka/reconstruct/"
  - "nyoka/skl/tests/"
  - "nyoka/tests/test_import.py"
  - "nyoka/tests/_validateSchema.py"
  - "nyoka/tests/_install_dependencies.py"
  - "nyoka/build.py"
  - "nyoka/PMML44.py"
  - "nyoka/PMML44Super.py"
  - "nyoka/Base64.py"
